// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ihbdrcfvktbuqzahtarp

class SupabaseConfig {
  static const String supabaseUrl = 'https://ihbdrcfvktbuqzahtarp.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloYmRyY2Z2a3RidXF6YWh0YXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMzI0NzAsImV4cCI6MjA3NzkwODQ3MH0.9PuhavPyb42zEoCUQa2IewvNtEHdfjbSh9xb7g1Lvj0';
}
